openapi: "3.0.2"
info:
  title: "lmu.localprintservice"
  description: >
    REST API for silent printing of PDF files from a JavaScript Frontend.
  version: "1.0.0dev0"
servers:
  - url: http://localhost:6543/api/v1
    description: Local Development Instance
  - url: https://localhost:6543/api/v1
    description: Local Development Instance (https)
paths:
  /printers:
    get:
      summary: List of Printers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "Printer 1"

  /printpdf:
    post:
      summary: Silent Print of the provided PDF on designated printer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                printer:
                  type: string
                  example: Printer 1
                file:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
    put:
      summary: Silent Print of the provided PDF to the default printer
      parameters:
          - in: query
            name: printer
            schema:
              type: string
            required: false
            description: designated printer
      requestBody:
        content:
          application/pdf:
            schema:
              type: string
              format: binary
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
